- hosts: localhost
  vars:
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
    personal: "{{ lookup('env', 'HOME') }}/personal"
  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      cache_valid_time: 432000
      state: present
    tags:
      - install
      - core
  tasks:
    - include_tasks: tasks/ssh.yml
      tags:
        - ssh
    - include_tasks: tasks/git.yml
      tags:
        - git
    - include_tasks: tasks/core.yml
      tags:
        - core
    - include_tasks: tasks/cargo.yml
      tags:
        - cargo
    - include_tasks: tasks/zsh.yml
      tags:
        - zsh
    - include_tasks: tasks/nvim.yml
      tags:
        - nvim
    - include_tasks: tasks/dotfiles.yml
      tags:
        - dotfiles
    - include_tasks: tasks/productivity.yml
      tags:
        - productivity
