- name: Check if cargo is installed
  shell: command -v cargo
  register: cargo_exists
  ignore_errors: true
  tags:
    - rust

- name: Install Starship
  when: cargo_exists
  shell: cargo install starship --locked
  tags:
    - rust
